"""Update

Revision ID: 5dd112ba0e34
Revises: 9c743cf80a7c
Create Date: 2024-07-20 14:48:38.955656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd112ba0e34'
down_revision: Union[str, None] = '9c743cf80a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'rating')
    # ### end Alembic commands ###
